name = "1.12.2"
author = "samueldelimpio"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d907fb4f5fc4bd31a89a8d6e8ced42982bd968aa1aa8f60974df458534278fd6"

[versions]
forge = "0.5.6-alpha"
minecraft = "1.12.2"
