name = "1.12.2"
author = "samueldelimpio"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5657ebd03349e4225001945a26b8dea681bb6193f988d123d1a9ef1a0aa29c5a"

[versions]
forge = "0.5.8-alpha"
minecraft = "1.12.2"
