name = "1.12.2"
author = "samueldelimpio"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "39b1c75533b9eaa0a218117ce9c4cfc6a7f24abb5be8ab6dfb12761460bc754f"

[versions]
forge = "0.5.6-alpha"
minecraft = "1.12.2"
